export const AUTH = {
	LOGIN: 'AUTH/LOGIN',
	REGISTER: 'AUTH/REGISTER',
	LOGOUT: 'AUTH/LOGOUT',
	UPDATE: 'AUTH/UPDATE_USER',
};

export const CHAT = {
	FETCH_CHATS: 'CHAT/FETCH_CHATS',
	SET_CURRENT_CHAT: 'CHAT/SET_CURRENT_CHAT',
};
