export const AUTH = {
	LOGIN: 'AUTH/LOGIN',
	REGISTER: 'AUTH/REGISTER',
	LOGOUT: 'AUTH/LOGOUT',
	UPDATE: 'AUTH/UPDATE_USER',
};

export const CHAT = {
	FETCH_CHATS: 'CHAT/FETCH_CHATS',
	SET_CURRENT_CHAT: 'CHAT/SET_CURRENT_CHAT',
	FRIENDS_ONLINE: 'CHAT/FRIENDS_ONLINE',
	FRIEND_ONLINE: 'CHAT/FRIEND_ONLINE',
	FRIEND_OFFLINE: 'CHAT/FRIEND_OFFLINE',
	SET_SOCKET: 'CHAT/SET_SOCKET',
	RECEIVED_MESSAGE: 'CHAT/RECEIVED_MESSAGE',
	SET_CHAT_LOGOUT: 'CHAT/SET_CHAT_LOGOUT',
	SENDER_TYPING: 'CHAT/SENDER_TYPING',
	SCROLL_TOP_PAGINATE_MESSAGES:
		'CHAT/SCROLL_TOP_PAGINATE_MESSAGES',
};
